source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

pod 'AFNetworking', '~> 2.6.3'
pod 'JLRoutes', '~> 1.5.3'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'Masonry', '~> 0.6.2'
pod 'SDWebImage', '~> 3.7.3'
pod 'MJRefresh', '~> 3.0.6'
pod 'JSONModel', '~> 1.1.0'
pod 'iRate', '~> 1.11.4'
pod 'Aspects', '~> 1.4.1'
pod 'MSWeakTimer', '~> 1.1.0'
pod 'SSKeychain', '~> 1.2.3'
pod 'Reachability', '~> 3.2'
pod 'PDTSimpleCalendar', '~> 0.9.1'
pod 'SMS_SDK', '~> 1.1.1'
pod 'RKDropdownAlert', '~> 0.3.0'
pod 'LGAlertView', '~> 2.0.11'
